<?php

namespace AppBundle\Repository;

/**
 * AdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdressRepository extends \Doctrine\ORM\EntityRepository
{
}
