<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

	/**
	 * @param string $slug
	 * @return null|Category
	 */
	public function findOneBySlug($slug)
	{
		return $this->findOneBy(
			[
				"slug" => $slug
			]
		);
	}

	/**
	 * @return Category[]
	 */
	public function findTopCategories()
	{
		return $this->findBy(
			[
				"level" => 0,
			],
			[
				"rank" => "desc",
			]
		);
	}

	/**
	 * @param Category $category
	 * @return Category[]
	 */
	public function findByParentCategory(Category $category = null)
	{
		return $this->findBy(
			[
				"parentCategory" => $category,
			],
			[
				"rank" => "desc",
			]
		);
	}

}
