<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getParents(Category $category)
    {
        return $this->_em->createQuery("
            SELECT ancestor
            FROM AppBundle\Entity\Category child, AppBundle\Entity\Category ancestor
            WHERE child.left >= ancestor.left
                AND child.left <= ancestor.right
                AND child.id = :current
            ORDER BY ancestor.left")
            ->setParameter("current", $category->getId())
            ->getResult();
    }
}
