<?php

namespace AppBundle\Repository;

/**
 * ContactFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactFormRepository extends \Doctrine\ORM\EntityRepository
{
}
