<?php

namespace AppBundle\Repository;

/**
 * FAQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FAQRepository extends \Doctrine\ORM\EntityRepository
{
}
